/**
 * EcoReward Backend Server (Node.js/Express)
 * This server acts as the bridge between the physical IoT bin and the Web App.
 */

const express = require('express');
const cors = require('cors');
const { v4: uuidv4 } = require('uuid');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static('.')); // Serve the web app from the same server!

// In-memory database (For demo purposes; use MongoDB or SQLite for production)
let validTokens = [];
let userPoints = {}; // { USER123: 150 }

/**
 * 1. BIN ENDPOINT: Generated by the IoT Smart Bin
 * The bin calls this after weighing waste.
 */
app.post('/api/generate-qr', (req, res) => {
    const { type, weight } = req.body;
    
    // Calculate points based on weight and type
    const multipliers = { plastic: 10, metal: 20, paper: 5, glass: 15 };
    const points = Math.round((weight || 1.0) * (multipliers[type] || 10));
    
    const token = uuidv4().substring(0, 8); // Short unique token
    
    const newToken = {
        token: token,
        points: points,
        type: type,
        isUsed: false,
        createdAt: new Date()
    };
    
    validTokens.push(newToken);
    
    console.log(`[Bin] New waste: ${type}, ${weight}kg. Generated token: ${token} (${points} pts)`);
    
    res.json({
        success: true,
        token: token,
        points: points,
        qrUrl: `https://your-web-app.com/reward?token=${token}&pts=${points}&type=${type}`
    });
});

/**
 * 2. WEB APP ENDPOINT: Claiming the reward
 * The web app calls this after the user scans the QR.
 */
app.post('/api/claim-reward', (req, res) => {
    const { uid, token } = req.body;
    
    if (!uid || !token) {
        return res.status(400).json({ success: false, message: "Missing User ID or Token" });
    }
    
    // Find valid token
    const tokenIndex = validTokens.findIndex(t => t.token === token && !t.isUsed);
    
    if (tokenIndex === -1) {
        return res.status(400).json({ success: false, message: "Invalid or already used QR code." });
    }
    
    const reward = validTokens[tokenIndex];
    reward.isUsed = true; // Mark as claimed
    
    // Update user points
    userPoints[uid] = (userPoints[uid] || 0) + reward.points;
    
    console.log(`[User] ${uid} claimed ${reward.points} pts for ${reward.type}. Total: ${userPoints[uid]}`);
    
    res.json({
        success: true,
        pointsEarned: reward.points,
        wasteType: reward.type,
        totalPoints: userPoints[uid],
        message: "Reward points added successfully!"
    });
});

/**
 * 3. GET USER POINTS: Fetch current balance
 */
app.get('/api/user/:uid', (req, res) => {
    const uid = req.params.uid;
    res.json({
        uid: uid,
        points: userPoints[uid] || 0
    });
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`EcoReward Backend running at http://0.0.0.0:${PORT}`);
    console.log(`- IoT Bin endpoint: http://10.124.34.38:${PORT}/api/generate-qr`);
    console.log(`- Web App endpoint: http://10.124.34.38:${PORT}/api/claim-reward`);
});
